# Generated by Django 3.0.7 on 2020-06-16 14:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispresso_upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrispressoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('fileNames', django.contrib.postgres.fields.jsonb.JSONField()),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
